name: Continous Deployment [REST] (CD)

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: "latest"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-auth-rest:latest -f RestDockerfile .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-auth-rest:latest

      - name: Deploy
        run: |
          gcloud run deploy heymart-auth-rest \
          --region europe-west1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-auth-rest \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --set-env-vars=DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --set-env-vars=SECRET_KEY=${{ secrets.SECRET_KEY }} \
          --set-env-vars=SALT=${{ secrets.SALT }} \
          --min-instances=1
